name: weather_app_programazione_exam_1
description: "A weather app for the programazione exam"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  flutter_spinkit: ^5.1.0 # For loading animations
  fluttertoast: ^8.2.1
  lottie: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/lang/en.json
      - assets/lang/it.json
      - assets/animations/



